### ISSUE TITLE
Invalid Plugin?

### ISSUE THREAD

**Issue by xthursdayx** [bookbrainz/CaliBBre#2]
When trying to install this plugin I get the following error: 
```
calibre, version 3.44.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'/Users/xthursdayx/Downloads/CaliBBre-master.zip' is invalid. It does not contain a top-level __init__.py file

calibre 3.44  embedded-python: True is64bit: True
Darwin-18.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.6.0', 'Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.5', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 17, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 17, 1) && Fantastic Fiction (1, 3, 0) && Barnes & Noble (1, 2, 15) && djvumaker (1, 0, 2) && Manage Series (1, 2, 8) && Kindle Collections (1, 7, 24) && Modify ePub (1, 3, 13) && Set KFX metadata (from KFX Output) (1, 30, 0) && KFX Output (1, 30, 0) && Find Duplicates (1, 6, 3) && Goodreads (1, 4, 0) && Goodreads Sync (1, 12, 1) && Count Pages (1, 8, 2) && Obok DeDRM (6, 5, 3) && Clean Metadata (0, 0, 6) && Extract ISBN (1, 4, 4) && Reading List (1, 6, 6) && Quality Check (1, 9, 11) && KFX metadata reader (from KFX Input) (1, 17, 1) && KFX Input (1, 17, 1)
Traceback (most recent call last):
  File "site-packages/calibre/gui2/preferences/plugins.py", line 318, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 472, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 61, in load_plugin
  File "site-packages/calibre/customize/zipplugin.py", line 194, in load
  File "site-packages/calibre/customize/zipplugin.py", line 292, in _locate_code
InvalidPlugin: The plugin in u'/Users/xthursdayx/Downloads/CaliBBre-master.zip' is invalid. It does not contain a top-level __init__.py file
```
Any ideas?

**Comment by k4j8** [comment]
I have this same error. If you download the zip file from GitHub (only option as far as I'm aware) and unzip it, all of the files are stored in a new directory called `CaliBBre-master`. I believe Calibre needs the files, including `__init__.py` to be unzipped in the same folder as `CaliBBre-master.zip`. This is how other plugins I have use worked.

I zipped the contents myself so the files would be on the top-level, but this did not resolve the issue mentioned above. Either there is a second issue going on or my above statements are wrong.

**Comment by R25114B** [comment]
Hopefully, some good news!! https://blog.metabrainz.org/2026/08/30/gsoc-2026-development-of-a-new-calibre-plugin-for-bookbrainz/
